version: "3"
services:
  admin:
<<<<<<< HEAD
    build:
      context: ../..
      dockerfile: public/assets/Dockerfile
=======
    build: .
>>>>>>> 835038c2e68d061091e2e27633b00e9a18feeed0
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
    - .:/code
    - /code/node_modules
<<<<<<< HEAD
    environment:
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web interface port
    restart: unless-stopped
=======
>>>>>>> 835038c2e68d061091e2e27633b00e9a18feeed0
